apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    okml.io/baseline: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: okml-readonly
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
